---
title: "Comparison_to_GTEx_human_specific"
author: "Lauren Blake"
date: "April 28, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The goal of this script is to compare the conserved tissue specific data with the tissue's ranking in the GTEx data v6 data. 

```{r cars}
# Import GTEx data

gtex_data <- read.csv("../data/GTEx_genes_tissues.csv", stringsAsFactors = FALSE)

# Find which genes are in both datasets

cpm_12184 <- read.delim("../../../Reg_Evo_Primates/data/cpm_12184.txt")

# Tissue up/downreg
heart_upreg_data <- read.csv("../data/human_specific_upreg_heart_genes.csv", stringsAsFactors = FALSE)
heart_downreg_data <- read.csv("../data/human_specific_downreg_heart_genes.csv", stringsAsFactors = FALSE)

kidney_upreg_data <- read.csv("../data/human_specific_upreg_kidney_genes.csv", stringsAsFactors = FALSE)
kidney_downreg_data <- read.csv("../data/human_specific_downreg_kidney_genes.csv", stringsAsFactors = FALSE)

liver_upreg_data <- read.csv("../data/human_specific_upreg_liver_genes.csv", stringsAsFactors = FALSE)
liver_downreg_data <- read.csv("../data/human_specific_downreg_liver_genes.csv", stringsAsFactors = FALSE)

lung_upreg_data <- read.csv("../data/human_specific_upreg_lung_genes.csv", stringsAsFactors = FALSE)
lung_downreg_data <- read.csv("../data/human_specific_downreg_lung_genes.csv", stringsAsFactors = FALSE)

```

# Overlap between GTEx and our dataset

```{r}
summary(rownames(cpm_12184) %in% gtex_data$ENSG)
```
11,777 genes are in both datasets.

# Upregulated in heart only
```{r}
# Subset 
summary(heart_upreg_data$x %in% gtex_data$ENSG)

inshared_lists = gtex_data$ENSG %in% heart_upreg_data$x
inshared_lists_data <- as.data.frame(inshared_lists)
counts_genes_in <- cbind(gtex_data, inshared_lists_data)
counts_genes_in_cutoff_pre <- subset(counts_genes_in, inshared_lists_data == "TRUE")
counts_genes_in_cutoff_pre <- counts_genes_in_cutoff_pre[,1:7]

# Is the heart the highest?

upreg_heart_ranking <- data.frame(counts_genes_in_cutoff_pre[,4:7], t(apply(-counts_genes_in_cutoff_pre[,4:7], 1, rank, ties.method='min')))

upreg_heart_ranking[,5]
```

# Downregulated in heart only
```{r}
# Subset 
summary(heart_downreg_data$x %in% gtex_data$ENSG)

inshared_lists = gtex_data$ENSG %in% heart_downreg_data$x
inshared_lists_data <- as.data.frame(inshared_lists)
counts_genes_in <- cbind(gtex_data, inshared_lists_data)
counts_genes_in_cutoff_pre <- subset(counts_genes_in, inshared_lists_data == "TRUE")
counts_genes_in_cutoff_pre <- counts_genes_in_cutoff_pre[,1:7]

# Is the heart the lowest?

downreg_heart_ranking <- data.frame(counts_genes_in_cutoff_pre[,4:7], t(apply(-counts_genes_in_cutoff_pre[,4:7], 1, rank, ties.method='min')))

downreg_heart_ranking[,5]
```
# Function for up/downregulation
```{r}

ranking_in_gtex <- function(tissue_name){
# Subset 
summary(tissue_name %in% gtex_data$ENSG)

inshared_lists = gtex_data$ENSG %in% tissue_name
inshared_lists_data <- as.data.frame(inshared_lists)
counts_genes_in <- cbind(gtex_data, inshared_lists_data)
counts_genes_in_cutoff_pre <- subset(counts_genes_in, inshared_lists_data == "TRUE")
counts_genes_in_cutoff_pre <- counts_genes_in_cutoff_pre[,1:7]

# Is the heart the highest?

upreg_heart_ranking <- data.frame(counts_genes_in_cutoff_pre[,4:7], t(apply(-counts_genes_in_cutoff_pre[,4:7], 1, rank, ties.method='min')))

return(upreg_heart_ranking)
}

upreg_heart_ranking <- ranking_in_gtex(heart_upreg_data$x)[,5]
downreg_heart_ranking <- ranking_in_gtex(heart_downreg_data$x)[,5]

upreg_kidney_ranking <- ranking_in_gtex(kidney_upreg_data$x)[,6]
downreg_kidney_ranking <- ranking_in_gtex(kidney_downreg_data$x)[,6]

upreg_liver_ranking <- ranking_in_gtex(liver_upreg_data$x)[,7]
downreg_liver_ranking <- ranking_in_gtex(liver_downreg_data$x)[,7]

upreg_lung_ranking <- ranking_in_gtex(lung_upreg_data$x)[,8]
downreg_lung_ranking <- ranking_in_gtex(lung_downreg_data$x)[,8]

```

# Ranking in our data
```{r}
# Heart
upreg_heart_num <- array(1, dim=c(length(upreg_heart_ranking), 1))

heart_cor1 <- cbind(upreg_heart_num, upreg_heart_ranking)

downreg_heart_num <- array(4, dim=c(length(downreg_heart_ranking), 1))

heart_cor2 <- cbind(downreg_heart_num, downreg_heart_ranking)

# Kidney
upreg_kidney_num <- array(1, dim=c(length(upreg_kidney_ranking), 1))

kidney_cor1 <- cbind(upreg_kidney_num, upreg_kidney_ranking)

downreg_kidney_num <- array(4, dim=c(length(downreg_kidney_ranking), 1))

kidney_cor2 <- cbind(downreg_kidney_num, downreg_kidney_ranking)

# Liver
upreg_liver_num <- array(1, dim=c(length(upreg_liver_ranking), 1))

liver_cor1 <- cbind(upreg_liver_num, upreg_liver_ranking)

downreg_liver_num <- array(4, dim=c(length(downreg_liver_ranking), 1))

liver_cor2 <- cbind(downreg_liver_num, downreg_liver_ranking)

# Lung
upreg_lung_num <- array(1, dim=c(length(upreg_lung_ranking), 1))

lung_cor1 <- cbind(upreg_lung_num, upreg_lung_ranking)

downreg_lung_num <- array(4, dim=c(length(downreg_lung_ranking), 1))

lung_cor2 <- cbind(downreg_lung_num, downreg_lung_ranking)

tissue_cor <- rbind(heart_cor1, heart_cor2, kidney_cor1, kidney_cor2, liver_cor1, liver_cor2, lung_cor1, lung_cor2)

# Get the correlation between tissues
cor(tissue_cor[,1], tissue_cor[,2])

# How many times does the ranking in our data match the ranking in GTEx?
summary(tissue_cor[,1] == tissue_cor[,2])

428/(259+428)
```
