---
title: "ASH_DE_RIN"
author: "Lauren Blake"
date: "June 7, 2017"
output: html_document
---



```{r chunk-options, include=FALSE}
source("chunk-options.R")
```


```{r}
# Load libraries

library("gplots")
library("ggplot2")
library("RColorBrewer")
library("scales")
library("edgeR")
library("R.utils")
library("plyr")
library("limma")
library("gridExtra")
library("VennDiagram")
source("functions.R")
library(ashr)
library(ggplot2)
library("topGO")
#library("biomaRt")
library("clusterProfiler")
library("org.Hs.eg.db")

# Set directory to save the data

data_dir <- "../data"

# Load colors 

colors <- colorRampPalette(c(brewer.pal(9, "Blues")[1],brewer.pal(9, "Blues")[9]))(100)
pal <- c(brewer.pal(9, "Set1"), brewer.pal(8, "Set2"), brewer.pal(12, "Set3"))

# Retrieve RIN score for each sample
RNA_seq_info <- read.csv("../../../Reg_Evo_Primates/data/RNA_seq_info.csv")
RIN <- as.data.frame(RNA_seq_info[,22])
RIN <- as.matrix(RIN)
colnames(RIN) <- c("RIN")

# Retrieve sample information
samples <- read.delim("../../../Reg_Evo_Primates/data/Sample_info_RNAseq_limma.txt")

# Eliminate H1H
samples <- samples[-17,]
dim(samples)

# Label species and tissues

species <- samples$Species
length(species)
tissue <- samples$Tissue
length(tissue)

labels <- paste(samples$Species, samples$Tissue, sep=" ")
```

## Test interactions

```{r}
## Make the contrast matrix and rename columns of the contrast matrix

design <- model.matrix(~ species*tissue + RIN)
colnames(design)[1] <- "Intercept"
colnames(design)[2] <- "Human"
colnames(design)[3] <- "Rhesus"
colnames(design)[4] <- "Kidney"
colnames(design)[5] <- "Liver"
colnames(design)[6] <- "Lung"
colnames(design)[8] <- "H_by_K"
colnames(design)[9] <- "R_by_K"
colnames(design)[10] <- "H_by_Li"
colnames(design)[11] <- "R_by_Li"
colnames(design)[12] <- "H_by_Lu"
colnames(design)[13] <- "R_by_Lu"

# Look at the number of samples in each column 
colSums(design)
```


```{r}
# Load count data

counts_genes_in_cutoff <- read.delim("../../../Reg_Evo_Primates/data/counts_12184.txt")

# TMM 

dge_in_cutoff <- DGEList(counts=as.matrix(counts_genes_in_cutoff), genes=rownames(counts_genes_in_cutoff), group = as.character(t(labels)))
dge_in_cutoff <- calcNormFactors(dge_in_cutoff)

cpm_in_cutoff <- cpm(dge_in_cutoff, normalized.lib.sizes=TRUE, log=TRUE)
head(cpm_in_cutoff)
hist(cpm_in_cutoff, xlab = "Log2(CPM)", main = "Log2(CPM) values for genes meeting the filtering criteria", breaks = 100 )

# Voom with individual as a random variable

cpm.voom.cyclic <- voom(dge_in_cutoff, design, normalize.method="cyclicloess", plot=T)

#corfit <- duplicateCorrelation(cpm.voom.cyclic, design, block=samples$Individual)
corfit.consensus <- 0.2197275

# Final voom on filtered data

cpm.voom.cyclic <- voom(dge_in_cutoff, design, normalize.method="cyclicloess", plot=TRUE, block=samples$Individual, correlation=corfit.consensus)

```



### Fit the linear model

```{r}
fit.cyclic.norm <- lmFit(cpm.voom.cyclic, design, plot = TRUE, block=samples$Individual, correlation=corfit.consensus)
fit.cyclic.norm <- eBayes(fit.cyclic.norm)


## - Potential caveat: variances could be different between human, chimp and rhesus (see Gordon Smyth email, 7 June 2013).                                                               
##  We look at the standard error for each condition                                                    
hist(fit.cyclic.norm$stdev.unscaled * fit.cyclic.norm$sigma, breaks=100)
hist(log2(fit.cyclic.norm$stdev.unscaled * fit.cyclic.norm$sigma), breaks=100)
boxplot(log2(fit.cyclic.norm$stdev.unscaled * fit.cyclic.norm$sigma))
## This seems to be pretty comparable between conditions. The human heart is higher, probably because of H1H missing and H3H with a bit strange behavior                                     
stderror <- log2(fit.cyclic.norm$stdev.unscaled * fit.cyclic.norm$sigma)
boxplot(list(stderror[,1:4], stderror[,5:8], stderror[,9:12]))
## A bit higher for human, and a bit lower for rhesus                                                                                                                                    
boxplot(list(stderror[,2:4], stderror[,6:8], stderror[,8:12])) ## excluding heart samples  
```

```{r}
# In the contrast matrix, we have many comparisons for species and tissues individually
# Note: baseline is chimp heart

cm1 <- makeContrasts(H_K_inter_CH = H_by_K, 
                     R_K_inter_CH = R_by_K, 
                     H_Li_inter_CH = H_by_Li, 
                     R_Li_inter_CH = R_by_Li,  
                     H_Lu_inter_CH = H_by_Lu, 
                     R_Lu_inter_CH = R_by_Lu,
                     levels = design)

# Implement contrasts

contrasts_each_species <- contrasts.fit(fit.cyclic.norm, cm1)
fit1 <- eBayes(contrasts_each_species)

top3 <- list(H_K_inter =topTable(fit1, coef=1, adjust="BH", number=Inf, sort.by="none"), 
             R_K_inter =topTable(fit1, coef=2, adjust="BH", number=Inf, sort.by="none"),  
             H_Li_inter =topTable(fit1, coef=3, adjust="BH", number=Inf, sort.by="none"),  
             R_Li_inter =topTable(fit1, coef=4, adjust="BH", number=Inf, sort.by="none"), 
             
             H_Lu_inter =topTable(fit1, coef=5, adjust="BH", number=Inf, sort.by="none"), 
             R_Lu_inter =topTable(fit1, coef=6, adjust="BH", number=Inf, sort.by="none") )


# Set FDR level at 1% 

FDR_level <- 0.01

## Significant interactions in Humans (baseline = chimp hearts)

mylist <- list()
mylist[["Kidney"]] <- row.names(top3[[names(top3)[1]]])[top3[[names(top3)[1]]]$adj.P.Val < FDR_level]
mylist[["Liver"]] <-  row.names(top3[[names(top3)[3]]])[top3[[names(top3)[3]]]$adj.P.Val < FDR_level]
mylist[["Lung"]] <- row.names(top3[[names(top3)[5]]])[top3[[names(top3)[5]]]$adj.P.Val < FDR_level]


# Make 
#dev.off()
Four_comp <- venn.diagram(mylist, filename= NULL, main="Significant interactions in Humans (FDR 1%)", cex=1.5 , fill = pal[1:3], lty=1, height=2000, width=3000)
grid.draw(Four_comp)

## Significant interactions in Rhesus (baseline = chimp hearts)

mylist <- list()
mylist[["Kidney"]] <- row.names(top3[[names(top3)[2]]])[top3[[names(top3)[2]]]$adj.P.Val < FDR_level]
mylist[["Liver"]] <-  row.names(top3[[names(top3)[4]]])[top3[[names(top3)[4]]]$adj.P.Val < FDR_level]
mylist[["Lung"]] <- row.names(top3[[names(top3)[6]]])[top3[[names(top3)[6]]]$adj.P.Val < FDR_level]


# Make 
dev.off()
Four_comp <- venn.diagram(mylist, filename= NULL, main="Significant interactions in Rhesus (FDR 1%)", cex=1.5 , fill = pal[1:3], lty=1, height=2000, width=3000)
grid.draw(Four_comp)

```



```{r}
# Perform multiple testing correction with adaptive shrinkage (ASH) 
 #
 # x - object MArrayLM from eBayes output
 # coef - coefficient tested by eBayes

run_ash <- function(x, coef){
  #stopifnot(class(x) == "MArrayLM", coef %in% colnames(x$coefficients),
  #             length(unique(x$df.total) == 1))
  result <- ash(betahat = x$coefficients[, coef], sebetahat = x$stdev.unscaled[, coef] * sqrt(x$s2.post), df = x$df.total[1])
  return(result)
}

get_results <- function(x, number = nrow(x$coefficients), sort.by = "none",
                        ...) {
  # x - object MArrayLM from eBayes output
  # ... - additional arguments passed to topTable
  stopifnot(class(x) == "MArrayLM")
  results <- topTable(x, number = number, sort.by = sort.by, ...)
  return(results)
}



# Prepare the data for the ASH
tests <- colnames(fit1$coefficients)
results <- vector(length = length(tests), mode = "list")
names(results) <- tests

# Get lfsr, lfdr, s value, q value, and a beta_est value. 
for (test in tests) {
  # Extract limma results
  results[[test]] <- get_results(fit1, coef = test)
  # Add mutliple testing correction with ASH
  output_ash <- run_ash(fit1, coef = test)
  results[[test]] <- cbind(results[[test]], sebetahat = output_ash$data$s, lfsr = output_ash$result$lfsr,
                           lfdr = output_ash$result$lfdr, qvalue = output_ash$result$qvalue,
                           svalue = output_ash$result$svalue, beta_est = output_ash$result$PosteriorMean, se_est =
                             output_ash$result$PosteriorSD)
}

# Save results from analysis with limma and ash.
#saveRDS(results, file.path(data_dir, #"results-limma-voom-ash-interactions.rds"))
```

# GO Enrichment for revisions

```{r}
FDR_level <- 0.05

human_kidney_inter <- top3$H_K_inter
human_liver_inter <- top3$H_Li_inter
human_lung_inter <- top3$H_Lu_inter

rhesus_kidney_inter <- top3$R_K_inter
rhesus_liver_inter <- top3$R_Li_inter
rhesus_lung_inter <- top3$R_Lu_inter

# Find human_kidney specific
human_kidney_only <- human_kidney_inter[which(human_kidney_inter$adj.P.Val < FDR_level & human_liver_inter$adj.P.Val > FDR_level & human_lung_inter$adj.P.Val > FDR_level & rhesus_kidney_inter$adj.P.Val > FDR_level & rhesus_liver_inter$adj.P.Val > FDR_level & rhesus_lung_inter$adj.P.Val > FDR_level), 1]                                   

human_kidney_inter_only <- human_kidney_inter$genes %in% human_kidney_only
```

## Human liver

```{r}

# Find human_kidney specific
human_liver_only <- human_liver_inter[which(human_kidney_inter$adj.P.Val > FDR_level & human_liver_inter$adj.P.Val < FDR_level & human_lung_inter$adj.P.Val > FDR_level & rhesus_kidney_inter$adj.P.Val > FDR_level & rhesus_liver_inter$adj.P.Val > FDR_level & rhesus_lung_inter$adj.P.Val > FDR_level), 1]                                   

human_liver_inter_only <- human_liver_inter$genes %in% human_liver_only

# Revisions- run GO
# Merge ENSG with true/false

test_gene <- as.numeric(as.vector(human_liver_inter_only))
names(test_gene) <- human_liver_inter$genes


# Run topGO
go_data <- new("topGOdata",
                   ontology = "BP",
                   allGenes = test_gene, 
                    geneSel = function(allScore){
    return(allScore > 0)
},
                   nodeSize = 5,
                   annotationFun = annFUN.org,
                   mapping = "org.Hs.eg.db",
                   ID = "ensembl")

# Perform enrichment test
go_test <- runTest(go_data, algorithm = "weight01", statistic = "fisher")

go_table <- GenTable(go_data, weightFisher = go_test,
                         orderBy = "weightFisher", ranksOf = "weightFisher",
                         topNodes = sum(score(go_test) < .01))

go_table

# Get names of liver genes
sig.genes <- sigGenes(go_data)
goresults <- sapply(go_table$GO.ID, function(x)
    {
      genes<-genesInTerm(go_data, x) 
      genes[[1]][genes[[1]] %in% sig.genes]
    })

goresults["GO:0005978"] 

# Gene to ID conversion document

gene_id <- read.table("../../../Reg_Evo_Primates/data/ENSG_GENE_HG19.csv", stringsAsFactors = FALSE, header=TRUE, sep = ",")

human_liver_only_data <- as.data.frame(c("ENSG00000079739", "ENSG00000114480", "ENSG00000132326", "ENSG00000142208"))
colnames(human_liver_only_data) <- c("ensg")

# Get gene names of the background
comb_liver <- merge(human_liver_only_data, gene_id, by = c("ensg"))

# glycogen biosynthetic proces

comb_liver
```

## Human lung

```{r}

# Find human_kidney specific
human_lung_only <- human_lung_inter[which(human_lung_inter$adj.P.Val < FDR_level & human_liver_inter$adj.P.Val > FDR_level & human_kidney_inter$adj.P.Val > FDR_level & rhesus_kidney_inter$adj.P.Val > FDR_level & rhesus_liver_inter$adj.P.Val > FDR_level & rhesus_lung_inter$adj.P.Val > FDR_level), 1]                                   

human_lung_inter_only <- human_lung_inter$genes %in% human_lung_only

# Revisions- run GO
# Merge ENSG with true/false

test_gene <- as.numeric(as.vector(human_lung_inter_only))
names(test_gene) <- human_lung_inter$genes


# Run topGO
go_data <- new("topGOdata",
                   ontology = "BP",
                   allGenes = test_gene, 
                    geneSel = function(allScore){
    return(allScore > 0)
},
                   nodeSize = 5,
                   annotationFun = annFUN.org,
                   mapping = "org.Hs.eg.db",
                   ID = "ensembl")

# Perform enrichment test
go_test <- runTest(go_data, algorithm = "weight01", statistic = "fisher")

go_table <- GenTable(go_data, weightFisher = go_test,
                         orderBy = "weightFisher", ranksOf = "weightFisher",
                         topNodes = sum(score(go_test) < .01))

go_table

sig.genes <- sigGenes(go_data)

goresults["GO:0048340"] 
goresults["GO:0032736"] 
goresults["GO:0032753"] 

# Gene to ID conversion document

#gene_id <- read.table("../../../Reg_Evo_Primates/data/ENSG_GENE_HG19.csv", stringsAsFactors = FALSE, header=TRUE, sep = ",")

#human_lung_only_data <- as.data.frame(c("ENSG00000105698", "ENSG00000131165"))
#colnames(human_liver_only_data) <- c("ensg")

# Get gene names of the background
#comb_lung <- merge(human_lung_only_data, gene_id, by = c("ensg"))

#positive regulation of lipoprotein lipas...

#comb_lung
```


## Human kidney

```{r}

# Find human_kidney specific
human_kidney_only <- human_kidney_inter[which(human_kidney_inter$adj.P.Val < FDR_level & human_liver_inter$adj.P.Val > FDR_level & human_lung_inter$adj.P.Val > FDR_level & rhesus_kidney_inter$adj.P.Val > FDR_level & rhesus_liver_inter$adj.P.Val > FDR_level & rhesus_lung_inter$adj.P.Val > FDR_level), 1]                                   

human_kidney_inter_only <- human_kidney_inter$genes %in% human_kidney_only

# Revisions- run GO
# Merge ENSG with true/false

test_gene <- as.numeric(as.vector(human_kidney_inter_only))
names(test_gene) <- human_kidney_inter$genes


# Run topGO
go_data <- new("topGOdata",
                   ontology = "BP",
                   allGenes = test_gene, 
                    geneSel = function(allScore){
    return(allScore > 0)
},
                   nodeSize = 5,
                   annotationFun = annFUN.org,
                   mapping = "org.Hs.eg.db",
                   ID = "ensembl")

# Perform enrichment test
go_test <- runTest(go_data, algorithm = "weight01", statistic = "fisher")

go_table <- GenTable(go_data, weightFisher = go_test,
                         orderBy = "weightFisher", ranksOf = "weightFisher",
                         topNodes = sum(score(go_test) < .01))

go_table

# Get names of kidney genes
sig.genes <- sigGenes(go_data)
goresults <- sapply(go_table$GO.ID, function(x)
    {
      genes<-genesInTerm(go_data, x) 
      genes[[1]][genes[[1]] %in% sig.genes]
    })

goresults["GO:0098719"] 

# Gene to ID conversion document

#gene_id <- read.table("../../../Reg_Evo_Primates/data/ENSG_GENE_HG19.csv", stringsAsFactors = FALSE, header=TRUE, sep = ",")

#human_kidney_only_data <- as.data.frame(c("ENSG00000138031", "ENSG00000142875", "ENSG00000173175"))
#colnames(human_kidney_only_data) <- c("ensg")

# Get gene names of the background
#comb_kidney <- merge(human_kidney_only_data, gene_id, by = c("ensg"))

# renal water homeostasis

#comb_kidney

```





