---
title: "Conserved_human_specific_tDMRs"
author: "Lauren Blake"
date: "April 3, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Introduction

```{r}
# Import libraries

library("ggplot2")
library("VennDiagram")
library("RColorBrewer")
library(plyr)
library("bedr")
getwd()

# Load colors 

colors <- colorRampPalette(c(brewer.pal(9, "Blues")[1],brewer.pal(9, "Blues")[9]))(100)
pal <- c(brewer.pal(9, "Set1"), brewer.pal(8, "Set2"), brewer.pal(12, "Set3"))

# Import the data

# Human tDMRs
humans_heart_kidney_DMRs <- read.delim("../data/humans_heart_kidney_DMRs.txt")
humans_heart_liver_DMRs <- read.delim("../data/humans_heart_liver_DMRs.txt")
humans_heart_lung_DMRs <- read.delim("../data/humans_heart_lung_DMRs.txt")
humans_liver_lung_DMRs <- read.delim("../data/humans_liver_lung_DMRs.txt")
humans_liver_kidney_DMRs <- read.delim("../data/humans_liver_kidney_DMRs.txt")
humans_lung_kidney_DMRs <- read.delim("../data/humans_lung_kidney_DMRs.txt")

levels(humans_lung_kidney_DMRs[,1])
count(humans_lung_kidney_DMRs[,1])

# Chimp tDMRs
chimps_heart_kidney_DMRs <- read.delim("../data/chimps_heart_kidney_DMRs.txt")
chimps_heart_liver_DMRs <- read.delim("../data/chimps_heart_liver_DMRs.txt")
chimps_heart_lung_DMRs <- read.delim("../data/chimps_heart_lung_DMRs.txt")
chimps_liver_lung_DMRs <- read.delim("../data/chimps_liver_lung_DMRs.txt")
chimps_liver_kidney_DMRs <- read.delim("../data/chimps_liver_kidney_DMRs.txt")
chimps_lung_kidney_DMRs <- read.delim("../data/chimps_lung_kidney_DMRs.txt")

levels(chimps_lung_kidney_DMRs[,1])
count(chimps_lung_kidney_DMRs[,1])

# Rhesus tDMRs

rhesus_heart_kidney_DMRs <- read.delim("../data/rhesus_heart_kidney_DMRs.txt")
rhesus_heart_liver_DMRs <- read.delim("../data/rhesus_heart_liver_DMRs.txt")
rhesus_heart_lung_DMRs <- read.delim("../data/rhesus_heart_lung_DMRs.txt")
rhesus_liver_lung_DMRs <- read.delim("../data/rhesus_liver_lung_DMRs.txt")
rhesus_liver_kidney_DMRs <- read.delim("../data/rhesus_liver_kidney_DMRs.txt")
rhesus_lung_kidney_DMRs <- read.delim("../data/rhesus_lung_kidney_DMRs.txt")

levels(rhesus_heart_kidney_DMRs[,1])
count(rhesus_lung_kidney_DMRs[,1])
```


# Get human, chimp, and rhesus autosomal tDMRs 


```{r}
# Human heart-liver

# columns to pull
pull_col <- c(1:3, 16)

# make bed style format
humans_heart_liver_DMRs_bed <- humans_heart_liver_DMRs[,pull_col]

# Get DMRs on the autosomal chromosomes only
humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed[which(humans_heart_liver_DMRs_bed[,1] != "chrX"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

summary(humans_heart_liver_DMRs_bed_noX[,3] - humans_heart_liver_DMRs_bed_noX[,2])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr11_gl000202_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr17_gl000204_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

sort_humans_heart_liver_DMRs_bed <- bedr.sort.region(humans_heart_liver_DMRs_bed_noX)

# Human heart-lung

# columns to pull
pull_col <- c(1:3, 16)

# make bed style format
humans_heart_liver_DMRs_bed <- humans_heart_lung_DMRs[,pull_col]

# Get DMRs on the autosomal chromosomes only
humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed[which(humans_heart_liver_DMRs_bed[,1] != "chrX"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr11_gl000202_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr17_gl000204_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

sort_humans_heart_lung_DMRs_bed <- bedr.sort.region(humans_heart_liver_DMRs_bed_noX)

# human heart-kidney

# columns to pull
pull_col <- c(1:3, 16)

# make bed style format
humans_heart_liver_DMRs_bed <- humans_heart_kidney_DMRs[,pull_col]

# Get DMRs on the autosomal chromosomes only
humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed[which(humans_heart_liver_DMRs_bed[,1] != "chrX"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr11_gl000202_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr17_gl000204_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

summary(humans_heart_liver_DMRs_bed_noX[,3] - humans_heart_liver_DMRs_bed_noX[,2])

sort_humans_heart_kidney_DMRs_bed <- bedr.sort.region(humans_heart_liver_DMRs_bed_noX, check.chr = FALSE)


# human liver-lung

# columns to pull
pull_col <- c(1:3, 16)

# make bed style format
humans_heart_liver_DMRs_bed <- humans_liver_lung_DMRs[,pull_col]

# Get DMRs on the autosomal chromosomes only
humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed[which(humans_heart_liver_DMRs_bed[,1] != "chrX"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

summary(humans_heart_liver_DMRs_bed_noX[,3] - humans_heart_liver_DMRs_bed_noX[,2])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr11_gl000202_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr17_gl000204_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

sort_humans_liver_lung_DMRs_bed <- bedr.sort.region(humans_heart_liver_DMRs_bed_noX)


# human liver-kidney

# columns to pull
pull_col <- c(1:3, 16)

# make bed style format
humans_heart_liver_DMRs_bed <- humans_liver_kidney_DMRs[,pull_col]

# Get DMRs on the autosomal chromosomes only
humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed[which(humans_heart_liver_DMRs_bed[,1] != "chrX"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

summary(humans_heart_liver_DMRs_bed_noX[,3] - humans_heart_liver_DMRs_bed_noX[,2])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr11_gl000202_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr17_gl000204_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

sort_humans_liver_kidney_DMRs_bed <- bedr.sort.region(humans_heart_liver_DMRs_bed_noX)

# human lung-kidney

# columns to pull
pull_col <- c(1:3, 16)

# make bed style format
humans_heart_liver_DMRs_bed <- humans_lung_kidney_DMRs[,pull_col]

# Get DMRs on the autosomal chromosomes only
humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed[which(humans_heart_liver_DMRs_bed[,1] != "chrX"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr11_gl000202_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr17_gl000204_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])
summary(humans_heart_liver_DMRs_bed_noX[,3] - humans_heart_liver_DMRs_bed_noX[,2])

sort_humans_lung_kidney_DMRs_bed <- bedr.sort.region(humans_heart_liver_DMRs_bed_noX)

```


```{r}
# Chimp heart-liver

# columns to pull
pull_col <- c(1:3, 16)

# make bed style format
humans_heart_liver_DMRs_bed <- chimps_heart_liver_DMRs[,pull_col]

# Get DMRs on the autosomal chromosomes only
humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed[which(humans_heart_liver_DMRs_bed[,1] != "chrX"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

summary(humans_heart_liver_DMRs_bed_noX[,3] - humans_heart_liver_DMRs_bed_noX[,2])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr11_gl000202_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr17_gl000204_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

sort_chimps_heart_liver_DMRs_bed <- bedr.sort.region(humans_heart_liver_DMRs_bed_noX)

# Chimp heart-lung

# columns to pull
pull_col <- c(1:3, 16)

# make bed style format
humans_heart_liver_DMRs_bed <- chimps_heart_lung_DMRs[,pull_col]

# Get DMRs on the autosomal chromosomes only
humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed[which(humans_heart_liver_DMRs_bed[,1] != "chrX"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr11_gl000202_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr17_gl000204_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

sort_chimps_heart_lung_DMRs_bed <- bedr.sort.region(humans_heart_liver_DMRs_bed_noX)

# chimp heart-kidney

# columns to pull
pull_col <- c(1:3, 16)

# make bed style format
humans_heart_liver_DMRs_bed <- chimps_heart_kidney_DMRs[,pull_col]

# Get DMRs on the autosomal chromosomes only
humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed[which(humans_heart_liver_DMRs_bed[,1] != "chrX"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr11_gl000202_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr17_gl000204_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

summary(humans_heart_liver_DMRs_bed_noX[,3] - humans_heart_liver_DMRs_bed_noX[,2])

sort_chimps_heart_kidney_DMRs_bed <- bedr.sort.region(humans_heart_liver_DMRs_bed_noX, check.chr = FALSE)


# Chimp liver-lung

# columns to pull
pull_col <- c(1:3, 16)

# make bed style format
humans_heart_liver_DMRs_bed <- chimps_liver_lung_DMRs[,pull_col]

# Get DMRs on the autosomal chromosomes only
humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed[which(humans_heart_liver_DMRs_bed[,1] != "chrX"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

summary(humans_heart_liver_DMRs_bed_noX[,3] - humans_heart_liver_DMRs_bed_noX[,2])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr11_gl000202_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr17_gl000204_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

sort_chimps_liver_lung_DMRs_bed <- bedr.sort.region(humans_heart_liver_DMRs_bed_noX)


# chimp liver-kidney

# columns to pull
pull_col <- c(1:3, 16)

# make bed style format
humans_heart_liver_DMRs_bed <- chimps_liver_kidney_DMRs[,pull_col]

# Get DMRs on the autosomal chromosomes only
humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed[which(humans_heart_liver_DMRs_bed[,1] != "chrX"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

summary(humans_heart_liver_DMRs_bed_noX[,3] - humans_heart_liver_DMRs_bed_noX[,2])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr11_gl000202_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr17_gl000204_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

sort_chimps_liver_kidney_DMRs_bed <- bedr.sort.region(humans_heart_liver_DMRs_bed_noX)

# chimp lung-kidney

# columns to pull
pull_col <- c(1:3, 16)

# make bed style format
humans_heart_liver_DMRs_bed <- chimps_lung_kidney_DMRs[,pull_col]

# Get DMRs on the autosomal chromosomes only
humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed[which(humans_heart_liver_DMRs_bed[,1] != "chrX"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr11_gl000202_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr17_gl000204_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])
summary(humans_heart_liver_DMRs_bed_noX[,3] - humans_heart_liver_DMRs_bed_noX[,2])

sort_chimps_lung_kidney_DMRs_bed <- bedr.sort.region(humans_heart_liver_DMRs_bed_noX)
```

```{r}
# Chimp heart-liver

# columns to pull
pull_col <- c(1:3, 16)

# make bed style format
humans_heart_liver_DMRs_bed <- rhesus_heart_liver_DMRs[,pull_col]

# Get DMRs on the autosomal chromosomes only
humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed[which(humans_heart_liver_DMRs_bed[,1] != "chrX"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

summary(humans_heart_liver_DMRs_bed_noX[,3] - humans_heart_liver_DMRs_bed_noX[,2])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr11_gl000202_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr17_gl000204_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

sort_rhesus_heart_liver_DMRs_bed <- bedr.sort.region(humans_heart_liver_DMRs_bed_noX)

# Chimp heart-lung

# columns to pull
pull_col <- c(1:3, 16)

# make bed style format
humans_heart_liver_DMRs_bed <- rhesus_heart_lung_DMRs[,pull_col]

# Get DMRs on the autosomal chromosomes only
humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed[which(humans_heart_liver_DMRs_bed[,1] != "chrX"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr11_gl000202_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr17_gl000204_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

sort_rhesus_heart_lung_DMRs_bed <- bedr.sort.region(humans_heart_liver_DMRs_bed_noX)

# chimp heart-kidney

# columns to pull
pull_col <- c(1:3, 16)

# make bed style format
humans_heart_liver_DMRs_bed <- rhesus_heart_kidney_DMRs[,pull_col]

# Get DMRs on the autosomal chromosomes only
humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed[which(humans_heart_liver_DMRs_bed[,1] != "chrX"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr11_gl000202_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr17_gl000204_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

summary(humans_heart_liver_DMRs_bed_noX[,3] - humans_heart_liver_DMRs_bed_noX[,2])

sort_rhesus_heart_kidney_DMRs_bed <- bedr.sort.region(humans_heart_liver_DMRs_bed_noX, check.chr = FALSE)


# Chimp liver-lung

# columns to pull
pull_col <- c(1:3, 16)

# make bed style format
humans_heart_liver_DMRs_bed <- rhesus_liver_lung_DMRs[,pull_col]

# Get DMRs on the autosomal chromosomes only
humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed[which(humans_heart_liver_DMRs_bed[,1] != "chrX"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

summary(humans_heart_liver_DMRs_bed_noX[,3] - humans_heart_liver_DMRs_bed_noX[,2])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr11_gl000202_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr17_gl000204_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

sort_rhesus_liver_lung_DMRs_bed <- bedr.sort.region(humans_heart_liver_DMRs_bed_noX)


# chimp liver-kidney

# columns to pull
pull_col <- c(1:3, 16)

# make bed style format
humans_heart_liver_DMRs_bed <- rhesus_liver_kidney_DMRs[,pull_col]

# Get DMRs on the autosomal chromosomes only
humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed[which(humans_heart_liver_DMRs_bed[,1] != "chrX"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

summary(humans_heart_liver_DMRs_bed_noX[,3] - humans_heart_liver_DMRs_bed_noX[,2])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr11_gl000202_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr17_gl000204_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

sort_rhesus_liver_kidney_DMRs_bed <- bedr.sort.region(humans_heart_liver_DMRs_bed_noX)

# chimp lung-kidney

# columns to pull
pull_col <- c(1:3, 16)

# make bed style format
humans_heart_liver_DMRs_bed <- rhesus_lung_kidney_DMRs[,pull_col]

# Get DMRs on the autosomal chromosomes only
humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed[which(humans_heart_liver_DMRs_bed[,1] != "chrX"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr11_gl000202_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])

humans_heart_liver_DMRs_bed_noX <- humans_heart_liver_DMRs_bed_noX[which(humans_heart_liver_DMRs_bed_noX[,1] != "chr17_gl000204_random"),]

humans_heart_liver_DMRs_bed_noX[,1] <- as.character(humans_heart_liver_DMRs_bed_noX[,1])
humans_heart_liver_DMRs_bed_noX[,2] <- as.integer(humans_heart_liver_DMRs_bed_noX[,2])
humans_heart_liver_DMRs_bed_noX[,3] <- as.integer(humans_heart_liver_DMRs_bed_noX[,3])
summary(humans_heart_liver_DMRs_bed_noX[,3] - humans_heart_liver_DMRs_bed_noX[,2])

sort_rhesus_lung_kidney_DMRs_bed <- bedr.sort.region(humans_heart_liver_DMRs_bed_noX)
```

# Function (e.g. human specific versus conserved in 1 pair of tissues)

```{r}
# 1 bp fit 
tissue_conserved_1_overlap <- function(DMR1_human, DMR1_chimp, DMR1_rhesus){

# Human-chimp/human-rhesus

human_chimp_DMR <- bedr(input = list(a = DMR1_human, b = DMR1_chimp), method = "intersect",  params = "-wao", check.chr = FALSE)

human_chimp_DMR <- human_chimp_DMR[which(human_chimp_DMR[,6] != -1), ]

human_rhesus_DMR <- bedr(input = list(a = DMR1_human, b = DMR1_rhesus), method = "intersect",  params = "-wao", check.chr = FALSE)

human_rhesus_DMR <- human_rhesus_DMR[which(human_rhesus_DMR[,6] != -1), ]

chimp_rhesus_DMR <- bedr(input = list(a = DMR1_chimp, b = DMR1_rhesus), method = "intersect",  params = "-wao", check.chr = FALSE)

chimp_rhesus_DMR <- chimp_rhesus_DMR[which(chimp_rhesus_DMR[,6] != -1), ]

colnames(human_chimp_DMR) <- c("chr", "start", "end", "direction", "chr.b", "start.b", "end.b", "direction.b", "overlap")

colnames(human_rhesus_DMR) <- c("chr", "start", "end", "direction", "chr.b", "start.b", "end.b", "direction.b", "overlap")

colnames(chimp_rhesus_DMR) <- c("chr", "start", "end", "direction", "chr.b", "start.b", "end.b", "direction.b", "overlap")

human_chimp_DMR <- bedr.merge.region(human_chimp_DMR)
human_rhesus_DMR <- bedr.merge.region(human_rhesus_DMR)
chimp_rhesus_DMR <- bedr.merge.region(chimp_rhesus_DMR)

# Human-chimp-rhesus

human_chimp_rhesus1_DMR <- bedr(input = list(a = human_chimp_DMR, b = human_rhesus_DMR), method = "intersect",  params = "-wao", check.chr = FALSE)

human_chimp_rhesus1a_DMR <- human_chimp_rhesus1_DMR[which(human_chimp_rhesus1_DMR[,6] != -1), ]

human_chimp_rhesus2_DMR <- bedr(input = list(a = human_chimp_rhesus1a_DMR[,1:4], b = chimp_rhesus_DMR), method = "intersect",  params = "-wao", check.chr = FALSE)

human_chimp_rhesus2a_DMR <- human_chimp_rhesus2_DMR[which(human_chimp_rhesus2_DMR[,6] != -1), ]

nrow(human_chimp_rhesus2a_DMR)

# human_chimp_rhesus2a_DMR gives the number of H/C/R conserved tDMRs

# Conserved in only 2 species

human_chimp_only <- bedr(input = list(a = human_chimp_DMR, b = human_chimp_rhesus2a_DMR[,1:4]), method = "intersect",  params = "-wao", check.chr = FALSE)

human_chimp_only <- human_chimp_only[which(human_chimp_only[,6] == -1), ]

nrow(human_chimp_only)

human_rhesus_only <- bedr(input = list(a = human_rhesus_DMR, b = human_chimp_rhesus2a_DMR[,1:4]), method = "intersect",  params = "-wao", check.chr = FALSE)

human_rhesus_only <- human_rhesus_only[which(human_rhesus_only[,6] == -1), ]

nrow(human_rhesus_only)

chimp_rhesus_only <- bedr(input = list(a = chimp_rhesus_DMR, b = human_chimp_rhesus2a_DMR[,1:4]), method = "intersect",  params = "-wao", check.chr = FALSE)

chimp_rhesus_only <- chimp_rhesus_only[which(chimp_rhesus_only[,6] == -1), ]

nrow(chimp_rhesus_only)

# Species-specific

human_specific <- nrow(DMR1_human) - nrow(human_chimp_only) - nrow(human_rhesus_only) - nrow(human_chimp_rhesus2a_DMR)

chimp_specific <- nrow(DMR1_chimp) - nrow(human_chimp_only) - nrow(chimp_rhesus_only) - nrow(human_chimp_rhesus2a_DMR)

rhesus_specific <- nrow(DMR1_rhesus) - nrow(human_rhesus_only) - nrow(chimp_rhesus_only) - nrow(human_chimp_rhesus2a_DMR)

combine <- cbind(human_specific, chimp_specific, rhesus_specific, nrow(human_chimp_only), nrow(human_rhesus_only), nrow(chimp_rhesus_only), nrow(human_chimp_rhesus2a_DMR))

colnames(combine) <- c("human_specific", "chimp_specific", "rhesus_specific", "hc", "hr", "cr", "hcr_conserved")

return(combine)
}

# 25% overlap

tissue_conserved_25_overlap <- function(DMR1_human, DMR1_chimp, DMR1_rhesus){

# Human-chimp/human-rhesus

human_chimp_DMR <- bedr(input = list(a = DMR1_human, b = DMR1_chimp), method = "intersect",  params = "-wao -f 0.25 -F 0.25", check.chr = FALSE)

human_chimp_DMR <- human_chimp_DMR[which(human_chimp_DMR[,6] != -1), ]

human_rhesus_DMR <- bedr(input = list(a = DMR1_human, b = DMR1_rhesus), method = "intersect",  params = "-wao -f 0.25 -F 0.25", check.chr = FALSE)

human_rhesus_DMR <- human_rhesus_DMR[which(human_rhesus_DMR[,6] != -1), ]

chimp_rhesus_DMR <- bedr(input = list(a = DMR1_chimp, b = DMR1_rhesus), method = "intersect",  params = "-wao -f 0.25 -F 0.25", check.chr = FALSE)

chimp_rhesus_DMR <- chimp_rhesus_DMR[which(chimp_rhesus_DMR[,6] != -1), ]

colnames(human_chimp_DMR) <- c("chr", "start", "end", "direction", "chr.b", "start.b", "end.b", "direction.b", "overlap")

colnames(human_rhesus_DMR) <- c("chr", "start", "end", "direction", "chr.b", "start.b", "end.b", "direction.b", "overlap")

colnames(chimp_rhesus_DMR) <- c("chr", "start", "end", "direction", "chr.b", "start.b", "end.b", "direction.b", "overlap")

human_chimp_DMR <- bedr.merge.region(human_chimp_DMR)
human_rhesus_DMR <- bedr.merge.region(human_rhesus_DMR)
chimp_rhesus_DMR <- bedr.merge.region(chimp_rhesus_DMR)

# Human-chimp-rhesus

human_chimp_rhesus1_DMR <- bedr(input = list(a = human_chimp_DMR, b = human_rhesus_DMR), method = "intersect",  params = "-wao -f 0.25 -F 0.25", check.chr = FALSE)

human_chimp_rhesus1a_DMR <- human_chimp_rhesus1_DMR[which(human_chimp_rhesus1_DMR[,6] != -1), ]

human_chimp_rhesus2_DMR <- bedr(input = list(a = human_chimp_rhesus1a_DMR[,1:4], b = chimp_rhesus_DMR), method = "intersect",  params = "-wao -f 0.25 -F 0.25", check.chr = FALSE)

human_chimp_rhesus2a_DMR <- human_chimp_rhesus2_DMR[which(human_chimp_rhesus2_DMR[,6] != -1), ]

nrow(human_chimp_rhesus2a_DMR)

# human_chimp_rhesus2a_DMR gives the number of H/C/R conserved tDMRs

# Conserved in only 2 species

human_chimp_only <- bedr(input = list(a = human_chimp_DMR, b = human_chimp_rhesus2a_DMR[,1:4]), method = "intersect",  params = "-wao -f 0.25 -F 0.25", check.chr = FALSE)

human_chimp_only <- human_chimp_only[which(human_chimp_only[,6] == -1), ]

nrow(human_chimp_only)

human_rhesus_only <- bedr(input = list(a = human_rhesus_DMR, b = human_chimp_rhesus2a_DMR[,1:4]), method = "intersect",  params = "-wao -f 0.25 -F 0.25", check.chr = FALSE)

human_rhesus_only <- human_rhesus_only[which(human_rhesus_only[,6] == -1), ]

nrow(human_rhesus_only)

chimp_rhesus_only <- bedr(input = list(a = chimp_rhesus_DMR, b = human_chimp_rhesus2a_DMR[,1:4]), method = "intersect",  params = "-wao -f 0.25 -F 0.25", check.chr = FALSE)

chimp_rhesus_only <- chimp_rhesus_only[which(chimp_rhesus_only[,6] == -1), ]

nrow(chimp_rhesus_only)

# Species-specific

human_specific <- nrow(DMR1_human) - nrow(human_chimp_only) - nrow(human_rhesus_only) - nrow(human_chimp_rhesus2a_DMR)

chimp_specific <- nrow(DMR1_chimp) - nrow(human_chimp_only) - nrow(chimp_rhesus_only) - nrow(human_chimp_rhesus2a_DMR)

rhesus_specific <- nrow(DMR1_rhesus) - nrow(human_rhesus_only) - nrow(chimp_rhesus_only) - nrow(human_chimp_rhesus2a_DMR)

combine <- cbind(human_specific, chimp_specific, rhesus_specific, nrow(human_chimp_only), nrow(human_rhesus_only), nrow(chimp_rhesus_only), nrow(human_chimp_rhesus2a_DMR))

colnames(combine) <- c("human_specific", "chimp_specific", "rhesus_specific", "hc", "hr", "cr", "hcr_conserved")

return(combine)
}
```


## Run for all tissues

### 1% overlap- all


```{r}
# Heart-kidney

tissue_conserved_1_overlap(sort_humans_heart_kidney_DMRs_bed, sort_chimps_heart_kidney_DMRs_bed, sort_rhesus_heart_kidney_DMRs_bed)

#      human_specific chimp_specific rhesus_specific   hc   hr cr
#[1,]          18751           7585           15098 5269 3080 1654
#     hcr_conserved
#[1,]          3191

# Heart liver
tissue_conserved_1_overlap(sort_humans_heart_liver_DMRs_bed, sort_chimps_heart_liver_DMRs_bed, sort_rhesus_heart_liver_DMRs_bed)

#     human_specific chimp_specific rhesus_specific   hc   hr   cr
#[1,]           8652          12855           27802 5310 2876 4879
#     hcr_conserved
#[1,]          5723
     
     
# Heat lung
tissue_conserved_1_overlap(sort_humans_heart_lung_DMRs_bed, sort_chimps_heart_lung_DMRs_bed, sort_rhesus_heart_lung_DMRs_bed)

#     human_specific chimp_specific rhesus_specific   hc  hr  cr
#[1,]          10440           4927            4960 2294 763 592
#     hcr_conserved
#[1,]           711

# Liver lung
tissue_conserved_1_overlap(sort_humans_liver_lung_DMRs_bed, sort_chimps_liver_lung_DMRs_bed, sort_rhesus_liver_lung_DMRs_bed)

 #    human_specific chimp_specific rhesus_specific   hc   hr   cr
#[1,]           4476          11393           23572 3333 1683 4031
#     hcr_conserved
#[1,]          3350


# Liver-Kidney
tissue_conserved_1_overlap(sort_humans_liver_kidney_DMRs_bed, sort_chimps_liver_kidney_DMRs_bed, sort_rhesus_liver_kidney_DMRs_bed)

#     human_specific chimp_specific rhesus_specific   hc   hr   cr
#[1,]           7402          11956           26043 4360 2336 3719
#     hcr_conserved
#[1,]          3812

# Lung-kidney
tissue_conserved_1_overlap(sort_humans_lung_kidney_DMRs_bed, sort_chimps_lung_kidney_DMRs_bed, sort_rhesus_lung_kidney_DMRs_bed)

#     human_specific chimp_specific rhesus_specific   hc   hr   cr
#[1,]          10166           6361           11466 3027 1735 1095
#     hcr_conserved
#[1,]          1593
```

### 1% overlap in hypo methylated
```{r}
sort_humans_heart_kidney_DMRs_bed_hypo <- sort_humans_heart_kidney_DMRs_bed[which(sort_humans_heart_kidney_DMRs_bed[,4] == "hypo"),]

sort_chimps_heart_kidney_DMRs_bed_hypo <- sort_chimps_heart_kidney_DMRs_bed[which(sort_chimps_heart_kidney_DMRs_bed[,4] == "hypo"),]

sort_rhesus_heart_kidney_DMRs_bed_hypo <- sort_rhesus_heart_kidney_DMRs_bed[which(sort_rhesus_heart_kidney_DMRs_bed[,4] == "hypo"),]

# Heart-kidney

tissue_conserved_1_overlap(sort_humans_heart_kidney_DMRs_bed_hypo, sort_chimps_heart_kidney_DMRs_bed_hypo, sort_rhesus_heart_kidney_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific   hc   hr  cr
#[1,]           8337           3851            6633 2167 1191 803
#     hcr_conserved
#[1,]          1157

# Heart liver

sort_humans_heart_liver_DMRs_bed_hypo <- sort_humans_heart_liver_DMRs_bed[which(sort_humans_heart_liver_DMRs_bed[,4] == "hypo"),]

sort_chimps_heart_liver_DMRs_bed_hypo <- sort_chimps_heart_liver_DMRs_bed[which(sort_chimps_heart_liver_DMRs_bed[,4] == "hypo"),]

sort_rhesus_heart_liver_DMRs_bed_hypo <- sort_rhesus_heart_liver_DMRs_bed[which(sort_rhesus_heart_liver_DMRs_bed[,4] == "hypo"),]

tissue_conserved_1_overlap(sort_humans_heart_liver_DMRs_bed_hypo, sort_chimps_heart_liver_DMRs_bed_hypo, sort_rhesus_heart_liver_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific   hc   hr   cr
#[1,]           5291           6148           12367 2427 1440 2452
#     hcr_conserved
#[1,]          2537
     
     
# Heat lung

sort_humans_heart_lung_DMRs_bed_hypo <- sort_humans_heart_lung_DMRs_bed[which(sort_humans_heart_lung_DMRs_bed[,4] == "hypo"),]

sort_chimps_heart_lung_DMRs_bed_hypo <- sort_chimps_heart_lung_DMRs_bed[which(sort_chimps_heart_lung_DMRs_bed[,4] == "hypo"),]

sort_rhesus_heart_lung_DMRs_bed_hypo <- sort_rhesus_heart_lung_DMRs_bed[which(sort_rhesus_heart_lung_DMRs_bed[,4] == "hypo"),]

tissue_conserved_1_overlap(sort_humans_heart_lung_DMRs_bed_hypo, sort_chimps_heart_lung_DMRs_bed_hypo, sort_rhesus_heart_lung_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific   hc  hr  cr
#[1,]           6922           2936            2734 1589 472 357
#     hcr_conserved
#[1,]           505

# Liver lung
sort_humans_liver_lung_DMRs_bed_hypo <- sort_humans_liver_lung_DMRs_bed[which(sort_humans_liver_lung_DMRs_bed[,4] == "hypo"),]

sort_chimps_liver_lung_DMRs_bed_hypo <- sort_chimps_liver_lung_DMRs_bed[which(sort_chimps_liver_lung_DMRs_bed[,4] == "hypo"),]

sort_rhesus_liver_lung_DMRs_bed_hypo <- sort_rhesus_liver_lung_DMRs_bed[which(sort_rhesus_liver_lung_DMRs_bed[,4] == "hypo"),]

tissue_conserved_1_overlap(sort_humans_liver_lung_DMRs_bed_hypo, sort_chimps_liver_lung_DMRs_bed_hypo, sort_rhesus_liver_lung_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific   hc  hr   cr
#[1,]           2380           7168           13737 2364 953 2392
#     hcr_conserved
#[1,]          2393


# Liver-Kidney
sort_humans_liver_kidney_DMRs_bed_hypo <- sort_humans_liver_kidney_DMRs_bed[which(sort_humans_liver_kidney_DMRs_bed[,4] == "hypo"),]

sort_chimps_liver_kidney_DMRs_bed_hypo <- sort_chimps_liver_kidney_DMRs_bed[which(sort_chimps_liver_kidney_DMRs_bed[,4] == "hypo"),]

sort_rhesus_liver_kidney_DMRs_bed_hypo <- sort_rhesus_liver_kidney_DMRs_bed[which(sort_rhesus_liver_kidney_DMRs_bed[,4] == "hypo"),]

tissue_conserved_1_overlap(sort_humans_liver_kidney_DMRs_bed_hypo, sort_chimps_liver_kidney_DMRs_bed_hypo, sort_rhesus_liver_kidney_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific   hc  hr   cr
#[1,]           2213           6412           14142 1761 816 1957
#     hcr_conserved
#[1,]          1578

# Lung-kidney

sort_humans_lung_kidney_DMRs_bed_hypo <- sort_humans_lung_kidney_DMRs_bed[which(sort_humans_lung_kidney_DMRs_bed[,4] == "hypo"),]

sort_chimps_lung_kidney_DMRs_bed_hypo <- sort_chimps_lung_kidney_DMRs_bed[which(sort_chimps_lung_kidney_DMRs_bed[,4] == "hypo"),]

sort_rhesus_lung_kidney_DMRs_bed_hypo <- sort_rhesus_lung_kidney_DMRs_bed[which(sort_rhesus_lung_kidney_DMRs_bed[,4] == "hypo"),]

tissue_conserved_1_overlap(sort_humans_lung_kidney_DMRs_bed_hypo, sort_chimps_lung_kidney_DMRs_bed_hypo, sort_rhesus_lung_kidney_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific  hc  hr  cr
#[1,]           2940           2478            4440 696 445 386
#     hcr_conserved
#[1,]           340
```


### 1% overlap in hyper methylated
```{r}
sort_humans_heart_kidney_DMRs_bed_hypo <- sort_humans_heart_kidney_DMRs_bed[which(sort_humans_heart_kidney_DMRs_bed[,4] == "hyper"),]

sort_chimps_heart_kidney_DMRs_bed_hypo <- sort_chimps_heart_kidney_DMRs_bed[which(sort_chimps_heart_kidney_DMRs_bed[,4] == "hyper"),]

sort_rhesus_heart_kidney_DMRs_bed_hypo <- sort_rhesus_heart_kidney_DMRs_bed[which(sort_rhesus_heart_kidney_DMRs_bed[,4] == "hyper"),]

# Heart-kidney

tissue_conserved_1_overlap(sort_humans_heart_kidney_DMRs_bed_hypo, sort_chimps_heart_kidney_DMRs_bed_hypo, sort_rhesus_heart_kidney_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific   hc   hr  cr
#[1,]          10493           3777            8595 3114 1814 812
#     hcr_conserved
#[1,]          2018

# Heart liver

sort_humans_heart_liver_DMRs_bed_hypo <- sort_humans_heart_liver_DMRs_bed[which(sort_humans_heart_liver_DMRs_bed[,4] == "hyper"),]

sort_chimps_heart_liver_DMRs_bed_hypo <- sort_chimps_heart_liver_DMRs_bed[which(sort_chimps_heart_liver_DMRs_bed[,4] == "hyper"),]

sort_rhesus_heart_liver_DMRs_bed_hypo <- sort_rhesus_heart_liver_DMRs_bed[which(sort_rhesus_heart_liver_DMRs_bed[,4] == "hyper"),]

tissue_conserved_1_overlap(sort_humans_heart_liver_DMRs_bed_hypo, sort_chimps_heart_liver_DMRs_bed_hypo, sort_rhesus_heart_liver_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific   hc   hr   cr
#[1,]           3510           6851           15744 2924 1312 2308
#     hcr_conserved
#[1,]          3120
     
     
# Heat lung

sort_humans_heart_lung_DMRs_bed_hypo <- sort_humans_heart_lung_DMRs_bed[which(sort_humans_heart_lung_DMRs_bed[,4] == "hyper"),]

sort_chimps_heart_lung_DMRs_bed_hypo <- sort_chimps_heart_lung_DMRs_bed[which(sort_chimps_heart_lung_DMRs_bed[,4] == "hyper"),]

sort_rhesus_heart_lung_DMRs_bed_hypo <- sort_rhesus_heart_lung_DMRs_bed[which(sort_rhesus_heart_lung_DMRs_bed[,4] == "hyper"),]

tissue_conserved_1_overlap(sort_humans_heart_lung_DMRs_bed_hypo, sort_chimps_heart_lung_DMRs_bed_hypo, sort_rhesus_heart_lung_DMRs_bed_hypo)

 #    human_specific chimp_specific rhesus_specific  hc  hr  cr
#[1,]           3546           2005            2262 704 268 226
#     hcr_conserved
#[1,]           202

# Liver lung
sort_humans_liver_lung_DMRs_bed_hypo <- sort_humans_liver_lung_DMRs_bed[which(sort_humans_liver_lung_DMRs_bed[,4] == "hyper"),]

sort_chimps_liver_lung_DMRs_bed_hypo <- sort_chimps_liver_lung_DMRs_bed[which(sort_chimps_liver_lung_DMRs_bed[,4] == "hyper"),]

sort_rhesus_liver_lung_DMRs_bed_hypo <- sort_rhesus_liver_lung_DMRs_bed[which(sort_rhesus_liver_lung_DMRs_bed[,4] == "hyper"),]

tissue_conserved_1_overlap(sort_humans_liver_lung_DMRs_bed_hypo, sort_chimps_liver_lung_DMRs_bed_hypo, sort_rhesus_liver_lung_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific  hc  hr   cr
#[1,]           2182           4349           10052 988 656 1527
#     hcr_conserved
#[1,]           926


# Liver-Kidney
sort_humans_liver_kidney_DMRs_bed_hypo <- sort_humans_liver_kidney_DMRs_bed[which(sort_humans_liver_kidney_DMRs_bed[,4] == "hyper"),]

sort_chimps_liver_kidney_DMRs_bed_hypo <- sort_chimps_liver_kidney_DMRs_bed[which(sort_chimps_liver_kidney_DMRs_bed[,4] == "hyper"),]

sort_rhesus_liver_kidney_DMRs_bed_hypo <- sort_rhesus_liver_kidney_DMRs_bed[which(sort_rhesus_liver_kidney_DMRs_bed[,4] == "hyper"),]

tissue_conserved_1_overlap(sort_humans_liver_kidney_DMRs_bed_hypo, sort_chimps_liver_kidney_DMRs_bed_hypo, sort_rhesus_liver_kidney_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific   hc   hr   cr
#[1,]           5288           5680           12146 2619 1431 1636
#     hcr_conserved
#[1,]          2204

# Lung-kidney

sort_humans_lung_kidney_DMRs_bed_hypo <- sort_humans_lung_kidney_DMRs_bed[which(sort_humans_lung_kidney_DMRs_bed[,4] == "hyper"),]

sort_chimps_lung_kidney_DMRs_bed_hypo <- sort_chimps_lung_kidney_DMRs_bed[which(sort_chimps_lung_kidney_DMRs_bed[,4] == "hyper"),]

sort_rhesus_lung_kidney_DMRs_bed_hypo <- sort_rhesus_lung_kidney_DMRs_bed[which(sort_rhesus_lung_kidney_DMRs_bed[,4] == "hyper"),]

tissue_conserved_1_overlap(sort_humans_lung_kidney_DMRs_bed_hypo, sort_chimps_lung_kidney_DMRs_bed_hypo, sort_rhesus_lung_kidney_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific   hc   hr  cr
#[1,]           7256           3911            7085 2336 1264 685
#     hcr_conserved
#[1,]          1244
```



### 25% overlap
```{r}
# Heart-kidney

tissue_conserved_25_overlap(sort_humans_heart_kidney_DMRs_bed, sort_chimps_heart_kidney_DMRs_bed, sort_rhesus_heart_kidney_DMRs_bed)

#      human_specific chimp_specific rhesus_specific   hc   hr cr
#[1,]          20415           9070           16631 4909 2672 1425
#     hcr_conserved
#[1,]          2295

# Heart liver
tissue_conserved_25_overlap(sort_humans_heart_liver_DMRs_bed, sort_chimps_heart_liver_DMRs_bed, sort_rhesus_heart_liver_DMRs_bed)

#     human_specific chimp_specific rhesus_specific   hc   hr   cr
#[1,]          10676          15186           30727 5517 2489 4185
#     hcr_conserved
#[1,]          3879
     
     
# Heat lung
tissue_conserved_25_overlap(sort_humans_heart_lung_DMRs_bed, sort_chimps_heart_lung_DMRs_bed, sort_rhesus_heart_lung_DMRs_bed)

#     human_specific chimp_specific rhesus_specific   hc  hr  cr
#[1,]          11053           5474            5399 2062 639 534
#     hcr_conserved
#[1,]           454

# Liver lung
tissue_conserved_25_overlap(sort_humans_liver_lung_DMRs_bed, sort_chimps_liver_lung_DMRs_bed, sort_rhesus_liver_lung_DMRs_bed)

#     human_specific chimp_specific rhesus_specific   hc   hr   cr
#[1,]           5752          13218           25690 3424 1481 3280
#     hcr_conserved
#[1,]          2185

# Liver-Kidney
tissue_conserved_25_overlap(sort_humans_liver_kidney_DMRs_bed, sort_chimps_liver_kidney_DMRs_bed, sort_rhesus_liver_kidney_DMRs_bed)

#     human_specific chimp_specific rhesus_specific   hc   hr   cr
#[1,]           5752          13218           25690 3424 1481 3280
#     hcr_conserved
#[1,]          2185

# Lung-kidney
tissue_conserved_25_overlap(sort_humans_lung_kidney_DMRs_bed, sort_chimps_lung_kidney_DMRs_bed, sort_rhesus_lung_kidney_DMRs_bed)

#     human_specific chimp_specific rhesus_specific   hc   hr  cr
#[1,]          11201           7216           12424 2795 1400 940
#     hcr_conserved
#[1,]          1125
```



### 25% overlap in hypo methylated
```{r}
sort_humans_heart_kidney_DMRs_bed_hypo <- sort_humans_heart_kidney_DMRs_bed[which(sort_humans_heart_kidney_DMRs_bed[,4] == "hypo"),]

sort_chimps_heart_kidney_DMRs_bed_hypo <- sort_chimps_heart_kidney_DMRs_bed[which(sort_chimps_heart_kidney_DMRs_bed[,4] == "hypo"),]

sort_rhesus_heart_kidney_DMRs_bed_hypo <- sort_rhesus_heart_kidney_DMRs_bed[which(sort_rhesus_heart_kidney_DMRs_bed[,4] == "hypo"),]

# Heart-kidney

tissue_conserved_25_overlap(sort_humans_heart_kidney_DMRs_bed_hypo, sort_chimps_heart_kidney_DMRs_bed_hypo, sort_rhesus_heart_kidney_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific   hc   hr  cr
#[1,]           9025           4520            7252 1964 1038 669
#     hcr_conserved
#[1,]           825

# Heart liver

sort_humans_heart_liver_DMRs_bed_hypo <- sort_humans_heart_liver_DMRs_bed[which(sort_humans_heart_liver_DMRs_bed[,4] == "hypo"),]

sort_chimps_heart_liver_DMRs_bed_hypo <- sort_chimps_heart_liver_DMRs_bed[which(sort_chimps_heart_liver_DMRs_bed[,4] == "hypo"),]

sort_rhesus_heart_liver_DMRs_bed_hypo <- sort_rhesus_heart_liver_DMRs_bed[which(sort_rhesus_heart_liver_DMRs_bed[,4] == "hypo"),]

tissue_conserved_25_overlap(sort_humans_heart_liver_DMRs_bed_hypo, sort_chimps_heart_liver_DMRs_bed_hypo, sort_rhesus_heart_liver_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific   hc   hr   cr
#[1,]           6214           7204           13610 2421 1247 2126
#     hcr_conserved
#[1,]          1813
     
     
# Heat lung

sort_humans_heart_lung_DMRs_bed_hypo <- sort_humans_heart_lung_DMRs_bed[which(sort_humans_heart_lung_DMRs_bed[,4] == "hypo"),]

sort_chimps_heart_lung_DMRs_bed_hypo <- sort_chimps_heart_lung_DMRs_bed[which(sort_chimps_heart_lung_DMRs_bed[,4] == "hypo"),]

sort_rhesus_heart_lung_DMRs_bed_hypo <- sort_rhesus_heart_lung_DMRs_bed[which(sort_rhesus_heart_lung_DMRs_bed[,4] == "hypo"),]

tissue_conserved_25_overlap(sort_humans_heart_lung_DMRs_bed_hypo, sort_chimps_heart_lung_DMRs_bed_hypo, sort_rhesus_heart_lung_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific   hc  hr  cr
#[1,]           7319           3287            3013 1446 401 332
#     hcr_conserved
#[1,]           322

# Liver lung
sort_humans_liver_lung_DMRs_bed_hypo <- sort_humans_liver_lung_DMRs_bed[which(sort_humans_liver_lung_DMRs_bed[,4] == "hypo"),]

sort_chimps_liver_lung_DMRs_bed_hypo <- sort_chimps_liver_lung_DMRs_bed[which(sort_chimps_liver_lung_DMRs_bed[,4] == "hypo"),]

sort_rhesus_liver_lung_DMRs_bed_hypo <- sort_rhesus_liver_lung_DMRs_bed[which(sort_rhesus_liver_lung_DMRs_bed[,4] == "hypo"),]

tissue_conserved_25_overlap(sort_humans_liver_lung_DMRs_bed_hypo, sort_chimps_liver_lung_DMRs_bed_hypo, sort_rhesus_liver_lung_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific   hc  hr   cr
#[1,]           3188           8367           15115 2460 870 1918
#     hcr_conserved
#[1,]          1572


# Liver-Kidney
sort_humans_liver_kidney_DMRs_bed_hypo <- sort_humans_liver_kidney_DMRs_bed[which(sort_humans_liver_kidney_DMRs_bed[,4] == "hypo"),]

sort_chimps_liver_kidney_DMRs_bed_hypo <- sort_chimps_liver_kidney_DMRs_bed[which(sort_chimps_liver_kidney_DMRs_bed[,4] == "hypo"),]

sort_rhesus_liver_kidney_DMRs_bed_hypo <- sort_rhesus_liver_kidney_DMRs_bed[which(sort_rhesus_liver_kidney_DMRs_bed[,4] == "hypo"),]

tissue_conserved_25_overlap(sort_humans_liver_kidney_DMRs_bed_hypo, sort_chimps_liver_kidney_DMRs_bed_hypo, sort_rhesus_liver_kidney_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific   hc  hr   cr
#[1,]           2841           7349           15184 1772 722 1554
#     hcr_conserved
#[1,]          1033

# Lung-kidney

sort_humans_lung_kidney_DMRs_bed_hypo <- sort_humans_lung_kidney_DMRs_bed[which(sort_humans_lung_kidney_DMRs_bed[,4] == "hypo"),]

sort_chimps_lung_kidney_DMRs_bed_hypo <- sort_chimps_lung_kidney_DMRs_bed[which(sort_chimps_lung_kidney_DMRs_bed[,4] == "hypo"),]

sort_rhesus_lung_kidney_DMRs_bed_hypo <- sort_rhesus_lung_kidney_DMRs_bed[which(sort_rhesus_lung_kidney_DMRs_bed[,4] == "hypo"),]

tissue_conserved_25_overlap(sort_humans_lung_kidney_DMRs_bed_hypo, sort_chimps_lung_kidney_DMRs_bed_hypo, sort_rhesus_lung_kidney_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific  hc  hr  cr
#[1,]           3232           2738            4717 612 344 317
#     hcr_conserved
#[1,]           233
```


### 25% overlap in hyper methylated
```{r}
sort_humans_heart_kidney_DMRs_bed_hypo <- sort_humans_heart_kidney_DMRs_bed[which(sort_humans_heart_kidney_DMRs_bed[,4] == "hyper"),]

sort_chimps_heart_kidney_DMRs_bed_hypo <- sort_chimps_heart_kidney_DMRs_bed[which(sort_chimps_heart_kidney_DMRs_bed[,4] == "hyper"),]

sort_rhesus_heart_kidney_DMRs_bed_hypo <- sort_rhesus_heart_kidney_DMRs_bed[which(sort_rhesus_heart_kidney_DMRs_bed[,4] == "hyper"),]

# Heart-kidney

tissue_conserved_25_overlap(sort_humans_heart_kidney_DMRs_bed_hypo, sort_chimps_heart_kidney_DMRs_bed_hypo, sort_rhesus_heart_kidney_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific   hc   hr  cr
#[1,]          11434           4582            9456 2949 1593 727
#     hcr_conserved
#[1,]          1463

# Heart liver

sort_humans_heart_liver_DMRs_bed_hypo <- sort_humans_heart_liver_DMRs_bed[which(sort_humans_heart_liver_DMRs_bed[,4] == "hyper"),]

sort_chimps_heart_liver_DMRs_bed_hypo <- sort_chimps_heart_liver_DMRs_bed[which(sort_chimps_heart_liver_DMRs_bed[,4] == "hyper"),]

sort_rhesus_heart_liver_DMRs_bed_hypo <- sort_rhesus_heart_liver_DMRs_bed[which(sort_rhesus_heart_liver_DMRs_bed[,4] == "hyper"),]

tissue_conserved_25_overlap(sort_humans_heart_liver_DMRs_bed_hypo, sort_chimps_heart_liver_DMRs_bed_hypo, sort_rhesus_heart_liver_DMRs_bed_hypo)

#    human_specific chimp_specific rhesus_specific   hc   hr   cr
#[1,]           4545           8063           17283 3112 1173 1992
#     hcr_conserved
#[1,]          2036
     
     
# Heat lung

sort_humans_heart_lung_DMRs_bed_hypo <- sort_humans_heart_lung_DMRs_bed[which(sort_humans_heart_lung_DMRs_bed[,4] == "hyper"),]

sort_chimps_heart_lung_DMRs_bed_hypo <- sort_chimps_heart_lung_DMRs_bed[which(sort_chimps_heart_lung_DMRs_bed[,4] == "hyper"),]

sort_rhesus_heart_lung_DMRs_bed_hypo <- sort_rhesus_heart_lung_DMRs_bed[which(sort_rhesus_heart_lung_DMRs_bed[,4] == "hyper"),]

tissue_conserved_25_overlap(sort_humans_heart_lung_DMRs_bed_hypo, sort_chimps_heart_lung_DMRs_bed_hypo, sort_rhesus_heart_lung_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific  hc  hr  cr
#[1,]           3752           2196            2409 615 223 196
#     hcr_conserved
#[1,]           130

# Liver lung
sort_humans_liver_lung_DMRs_bed_hypo <- sort_humans_liver_lung_DMRs_bed[which(sort_humans_liver_lung_DMRs_bed[,4] == "hyper"),]

sort_chimps_liver_lung_DMRs_bed_hypo <- sort_chimps_liver_lung_DMRs_bed[which(sort_chimps_liver_lung_DMRs_bed[,4] == "hyper"),]

sort_rhesus_liver_lung_DMRs_bed_hypo <- sort_rhesus_liver_lung_DMRs_bed[which(sort_rhesus_liver_lung_DMRs_bed[,4] == "hyper"),]

tissue_conserved_25_overlap(sort_humans_liver_lung_DMRs_bed_hypo, sort_chimps_liver_lung_DMRs_bed_hypo, sort_rhesus_liver_lung_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific  hc  hr   cr
#[1,]           2621           4927           10707 968 559 1291
#     hcr_conserved
#[1,]           604


# Liver-Kidney
sort_humans_liver_kidney_DMRs_bed_hypo <- sort_humans_liver_kidney_DMRs_bed[which(sort_humans_liver_kidney_DMRs_bed[,4] == "hyper"),]

sort_chimps_liver_kidney_DMRs_bed_hypo <- sort_chimps_liver_kidney_DMRs_bed[which(sort_chimps_liver_kidney_DMRs_bed[,4] == "hyper"),]

sort_rhesus_liver_kidney_DMRs_bed_hypo <- sort_rhesus_liver_kidney_DMRs_bed[which(sort_rhesus_liver_kidney_DMRs_bed[,4] == "hyper"),]

tissue_conserved_25_overlap(sort_humans_liver_kidney_DMRs_bed_hypo, sort_chimps_liver_kidney_DMRs_bed_hypo, sort_rhesus_liver_kidney_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific   hc   hr   cr
#[1,]           6073           6548           13114 2576 1288 1410
#     hcr_conserved
#[1,]          1605

# Lung-kidney

sort_humans_lung_kidney_DMRs_bed_hypo <- sort_humans_lung_kidney_DMRs_bed[which(sort_humans_lung_kidney_DMRs_bed[,4] == "hyper"),]

sort_chimps_lung_kidney_DMRs_bed_hypo <- sort_chimps_lung_kidney_DMRs_bed[which(sort_chimps_lung_kidney_DMRs_bed[,4] == "hyper"),]

sort_rhesus_lung_kidney_DMRs_bed_hypo <- sort_rhesus_lung_kidney_DMRs_bed[which(sort_rhesus_lung_kidney_DMRs_bed[,4] == "hyper"),]

tissue_conserved_25_overlap(sort_humans_lung_kidney_DMRs_bed_hypo, sort_chimps_lung_kidney_DMRs_bed_hypo, sort_rhesus_lung_kidney_DMRs_bed_hypo)

#     human_specific chimp_specific rhesus_specific   hc   hr  cr
#[1,]           7985           4495            7739 2184 1042 608
#     hcr_conserved
#[1,]           889
```

## Making plots

```{r}

# Hypo
#     human_specific chimp_specific rhesus_specific   hc   hr  cr
#[1,]           9025           4520            7252 1964 1038 669
#     hcr_conserved
#[1,]           825

sort_humans_heart_kidney_DMRs_bed_hypo <- sort_humans_heart_kidney_DMRs_bed[which(sort_humans_heart_kidney_DMRs_bed[,4] == "hypo"),]

sort_chimps_heart_kidney_DMRs_bed_hypo <- sort_chimps_heart_kidney_DMRs_bed[which(sort_chimps_heart_kidney_DMRs_bed[,4] == "hypo"),]

sort_rhesus_heart_kidney_DMRs_bed_hypo <- sort_rhesus_heart_kidney_DMRs_bed[which(sort_rhesus_heart_kidney_DMRs_bed[,4] == "hypo"),]

# Heart-kidney hypo
dev.off()
draw.triple.venn(nrow(sort_humans_heart_kidney_DMRs_bed_hypo), nrow(sort_chimps_heart_kidney_DMRs_bed_hypo), nrow(sort_rhesus_heart_kidney_DMRs_bed_hypo), 1964+825, 669+825, 1038+825, 825,  main= "Heart versus kidney (hypomethylated)",  category = c("Human", "Chimp", "Rhesus macaque"), height=3000, width=3000, cex=2 , fill = pal[1:3], lty=1, cat.cex = 2, main.cex = 2)


#Hyper
#     human_specific chimp_specific rhesus_specific   hc   hr  cr
#[1,]          11434           4582            9456 2949 1593 727
#     hcr_conserved
#[1,]          1463


sort_humans_heart_kidney_DMRs_bed_hypo <- sort_humans_heart_kidney_DMRs_bed[which(sort_humans_heart_kidney_DMRs_bed[,4] == "hyper"),]

sort_chimps_heart_kidney_DMRs_bed_hypo <- sort_chimps_heart_kidney_DMRs_bed[which(sort_chimps_heart_kidney_DMRs_bed[,4] == "hyper"),]

sort_rhesus_heart_kidney_DMRs_bed_hypo <- sort_rhesus_heart_kidney_DMRs_bed[which(sort_rhesus_heart_kidney_DMRs_bed[,4] == "hyper"),]

# # Other plots
dev.off()
draw.triple.venn(nrow(sort_humans_heart_kidney_DMRs_bed_hypo), nrow(sort_chimps_heart_kidney_DMRs_bed_hypo), nrow(sort_rhesus_heart_kidney_DMRs_bed_hypo), 2949+1463, 727+1463, 1593+1463, 1463,  main= "Heart versus kidney (hypomethylated)",  category = c("Human", "Chimp", "Rhesus macaque"), height=3000, width=3000, cex=2 , fill = pal[1:3], lty=1, cat.cex = 2, main.cex = 2)


dev.off()
draw.triple.venn(444+306+1083+200, 306+1083+577+457, 200+1083+577+947, 306+1083, 577+1083, 200+1083,1083,  main= "Heart versus kidney (hypomethylated)",  category = c("Human", "Chimp", "Rhesus macaque"), height=3000, width=3000, cex=2 , fill = pal[1:3], lty=1, cat.cex = 2, main.cex = 2)


```


